### ISSUE TITLE
Multi output functions

### ISSUE THREAD

**Issue by dezenn** [HaoZhongkai/GNOT#11]
I really like the concept of GNOT as it allows to combine multiple input functions and additionaly an input vector of scalars but is it able to learn to map to multiple output functions?

**Comment by HaoZhongkai** [comment]
Hi, 

 Thanks for your interest. If these outputs share the query points, we could learn them using a single MLP(multiple channels) or multiple MLPs( similar to multi-task learning). Otherwise, we might need to slightly modify the attention module to allow different query points.

 

best regards,

Zhongkai







-----原始邮件-----
发件人:dezenn ***@***.***>
发送时间:2024-05-29 20:38:46 (星期三)
收件人: HaoZhongkai/GNOT ***@***.***>
抄送: Subscribed ***@***.***>
主题: [HaoZhongkai/GNOT] Multi output functions (Issue #11)






I really like the concept of GNOT as it allows me to combine multiple inputs functions and a input vector of scalars but is it able to learn to multiple output functions?

**Comment by dezenn** [comment]
Hi,

thank your very much for your answer. 

With query points you mean something like grid points or time-steps right?

So what I basically want to learn is an operator of the following form $\mathcal{A}:\mathcal{C}([0,T])^n\times\mathbb{R}^l\rightarrow\mathcal{C}([0,T])^m$ with $n,m,l\in\mathbb{N}$ and $T\in\mathbb{R}$. This operator describes a simulation/system of differential equations.
Per data point/simulation all the functions in $\mathcal{C}([0,T])^n$ and $\mathcal{C}([0,T])^m$ would have the same time-steps they are evaluated on. The length, i.e. the amount of time-steps can differ per data point. So the first data point has for example the time-steps $[0,5,10,15]$ on which the $n$ and $m$ functions are evaluated on. The next data point could have for example the time-steps $[0,5,10,15,20,25,30,35]$. The way it is discretized is the 'same' but the length can vary. But since an attention module is used this should not cause any trouble. 

Now I wondered if I have to modify the GNOT code such that it can learn multiple target functions or if there is already something suitable implemented. 

Best regards, 
Dean

**Comment by HaoZhongkai** [comment]
Hi,
  If I understand correctly. For each data point, the query points (like [0,5,10,15] or [0,5,10,15...,35]) are the same. That means the input and output functions are defined on the same grid. So we could use different channels to represent different components of input/output functions.  So we do not need to modify anything of GNOT.

**Comment by dezenn** [comment]
@HaoZhongkai 

Hi,

thank you very much! Nice, then it seems that GNOT is suitable for my problem. I will let you know how it works.
